### PR TITLE
feat: publish on npm

### LINKED ISSUE #13: Publish on npm?
Hi, thanks for your awesome plugin!
I am making a eslint plugin to integrate dprint into eslint. The dprint plugins must be published on npm.
Can you publish this package on npm (like @dprint/json)? Thanks a lot!

### PR DESCRIPTION
**Pull request by so1ve**
resolves #13
If you want to change something, please push directly to this pr and mark it as "ready to review" 😊

### CODE REVIEW

**Comment by disrupted** [comment]
@so1ve sorry for the delay, I wanted to rebase your changes on `main` but I am unable to push to your branch.

**Comment by disrupted** [comment]
also I am wondering what do I need to do for the NPM token secret?

**Comment by so1ve** [comment]
> I am unable to push to your branch

 😨

> what do I need to do for the NPM token secret

Just add a repository secret called `NPM_TOKEN`, and the value should be your NPM token

**Comment by disrupted** [comment]
> > I am unable to push to your branch
> 
>  😨

still getting permission denied
 
> > what do I need to do for the NPM token secret
> 
> Just add a repository secret called `NPM_TOKEN`, and the value should be your NPM token

done ✔️ 

will have to continue in #16

**Comment by so1ve** [comment]
Thanks!

**Comment by disrupted** [comment]
thanks for your contribution

**Comment by disrupted** [comment]
publish failed :( turns out https://www.npmjs.com/package/dprint-plugin-css already exists but it's empty. any advice what to do? I have no experience with publishing packages on NPM

**Comment by so1ve** [comment]
> already exists

wow...

Maybe I can contact the author

**Comment by disrupted** [comment]
I went ahead and filed an NPM package name dispute now. I'll let you know how it turns out.

**Comment by disrupted** [comment]
might take a while....
> due to the nature and complexity of these requests, we are experiencing significant wait times of up to multiple months. We generally review requests in the order received.
> 
> Unfortunately, we do not have an expected wait time to share. Our team will contact you once your request has been reviewed.

perhaps it's still a good idea to contact the original author, ideally they are happy to hear this plugin now exists and would be willing to transfer ownership.

**Comment by so1ve** [comment]
I have sent an email to him - let's wait for response :)

**Comment by justjavac** [comment]
glad to see you develop this plugin. I have already removed the package

**Comment by disrupted** [comment]
great, thanks for the quick response!

**Comment by disrupted** [comment]
> dprint-plugin-css cannot be republished until 24 hours have passed

gotta wait a bit, will retry later

**Comment by disrupted** [comment]
it's published now!

**Pull request closed without merging**
